# Dollar Universe 6.10 Deployment Inventory

all:
  children:
    duas_servers:
      vars: {}
      hosts:
        cdg-oci-gold-c4f-le-iaas-vm1:
          ansible_host: 10.24.11.195
          ansible_user: c4f-admin